In [10]:
import argparse
import torch
import math
import numpy as np
import time
import pickle 
from torch.nn.functional import gumbel_softmax
from utils import gumbel_softmax_3d

In [27]:
class SKModel():
    def __init__(self, n=20, seed=0, device='cuda:0'):
        self.n = n
        self.seed = seed
        self.device = device
        if self.seed > 0:
            torch.manual_seed(self.seed)
        self.J = torch.randn(self.n, self.n) / math.sqrt(self.n)
        self.J = torch.triu(self.J, diagonal=1)
        self.J = self.J + self.J.t()
        self.J_np = self.J.numpy()

    def gumbel_optimization(self, bs=128, max_iters=20000, lr=1, eta=1e-3, init_tau=20, final_tau=1, diff=1e-8,elim_rate=0.125,mut_rate=1e-3):
        n = self.n
        device = self.device
        J = self.J.to(device)
        # learnable parameters
        # x = torch.randn(bs, n, 1, device=device, requires_grad=True)
        x = torch.randn(bs, n, 1, device=device) * 1e-5
        x.requires_grad = True
        optimizer = torch.optim.Adam([x], lr=lr)
        tau = init_tau
        decay = (init_tau - final_tau) / max_iters
        E_best = torch.ones(1, device=device)

        for i in range(max_iters):
            E_old = E_best.clone()
            optimizer.zero_grad()
            probs = torch.empty(bs, n, 2, device=device)
            p = torch.sigmoid(x)
            probs[:, :, 0] = p.squeeze()
            probs[:, :, -1] = 1 - probs[:, :, 0]
            logits = torch.log(probs + 1e-10)
            s = 2 * gumbel_softmax_3d(logits, tau=tau, hard=False)[:, :, 0] - 1
            E = -0.5 * torch.sum((s @ J) * s, dim=1) / n
            constraint = torch.sum(x ** 2) / n / bs
            loss = torch.mean(E) + eta * constraint
            optimizer = torch.optim.Adam([x], lr=lr)
            loss.backward()
            optimizer.step()
            tau -= decay
            with torch.no_grad():
                if i % 100 == 0:
                    print(i,'Current best result: %.8f' % (E_best.cpu().numpy()))
                s = 2 * gumbel_softmax_3d(logits, tau=tau, hard=True)[:, :, 0] - 1
                E = -0.5 * torch.sum((s @ J) * s, dim=1) / n
                Emin = torch.min(E)
                Emean = torch.mean(E)
                if i % 100 == 0:
                    E_np = E.cpu().numpy()
                    E_np_min = np.min(E_np)
                    E_sorted=np.sort(E_np)
                    index_sorted=np.argsort(E_np)
                    print('Energy_sorted:\n', E_sorted[0:16])
                    print('label_sorted:\n', index_sorted[0:16])
                    for i in index_sorted[0:16]:
                        print(i)
                        print(s[i,:])
                if Emin < E_best:
                    E_best = Emin
                
                ##############Evolution#############
                if i % 1000000000000 == 0 and E_old - Emin < 1e-6:
                    
                    
                    E_np = E.cpu().numpy()
                    E_sorted=np.sort(E_np)
                    index_sorted=np.argsort(E_np)
                    #print('Energy_sorted:\n', E_sorted)
                    #print('label_sorted:\n', index_sorted)
                    
                    
                    w = np.max(E_np) - E_np
                    fitness = w / np.sum(w)
                    
                    
                    #print('fitness:\n', fitness)
                    ac = 0
                    f = np.empty(bs)
                    #print('roulette:')
                    for i in range(bs):
                        f[i] = ac + fitness[i]
                        ac = f[i]
                        #print(i, f[i])
                    r = np.random.random()
                    
                    
                    #print('\nGA.select1:')
                    j = 0
                    z = np.ones(bs, dtype=int)
                    z = z * (bs + 1)
                    while j < bs * (1 - elim_rate):
                        r = np.random.random()
                        if 0 <= r < f[0]:
                            if 0 not in z:
                                z[j] = 0
                                j = j + 1
                                continue
                        elif f[bs - 1] <= r <= 1:
                            if (bs - 1) not in z:
                                z[j] = (bs - 1)
                                j = j + 1
                                continue
                        else:
                            for t in range(bs):
                                if f[t] <= r < f[t + 1]:
                                    if t not in z:
                                        z[j] = t
                                        j = j + 1
                                        break    
                    #print(z)
                    
                    
                    #print('\nGA.select2:')
                    k = 0
                    elim = int(bs * elim_rate)
                    u = np.ones(elim,dtype=int)
                    while k < bs * elim_rate:
                        q = np.random.random()
                        if 0 <= q < f[0]:
                            if 0 in z:                
                                u[k] = 0
                                k = k + 1
                                continue
                        elif f[bs - 1] <= q <= 1:
                            if (bs-1) in z:
                                u[k] = (bs - 1)
                                k = k + 1
                                continue
                        else:
                            for o in range(bs):
                                if f[o] <= q < f[o + 1]:
                                    if o in z:
                                        u[k] = o
                                        k = k + 1
                                        break
                    u = u.reshape(int(elim/2),2)
                    #print(u)
                    
                    
                    #print('\nGA.crossover:')
                    x_ = torch.empty(bs,n,1,device=device)
                    x_.requires_grad = True
                    for l in range(int(elim/2)):
                        n1 = u[l,0]
                        n2 = u[l,1]
                        x1 = x[n1,:,0].split(int(n/2))
                        x2 = x[n2,:,0].split(int(n/2))
                        x11 = x1[0]
                        x12 = x1[1]
                        x21 = x2[0]
                        x22 = x2[1]
                        x_1 = torch.cat((x11,x22))
                        x_2 = torch.cat((x21,x12))
                        x_[int(bs*(1-elim_rate))+2*l,:,0]=x_1
                        x_[int(bs*(1-elim_rate))+2*l+1,:,0]=x_2
                        for i in range(int(bs * (1 - elim_rate))):
                            x_[i,:,0]=x[z[i],:,0]
                    #print(x.size())
                    #print(x_.size())

                    
                    #print('\nGA.mutation:')
                    mut_count = 0
                    for i in range(bs):
                        for j in range(n):
                            if np.random.random() <= mut_rate:
                                x_[i,j,0] = torch.randn(1,device=device) * 1e-5
                                mut_count += 1
                    #print(mut_count)
                    
                    
                    #p_ = torch.sigmoid(x_)
                    #probs_ = torch.empty(bs, n, 2, device=device)
                    #probs_[:, :, 0] = p_.squeeze()
                    #probs_[:, :, -1] = 1 - probs_[:, :, 0]
                    #logits_ = torch.log(probs_ + 1e-10)
                    #s_ = 2 * gumbel_softmax_3d(logits_, tau=tau, hard=False)[:, :, 0] - 1
                    #E_ = -0.5 * torch.sum((s_ @ J) * s_, dim=1) / n
                    #if torch.mean(E_)<Emean or torch.min(E_)<Emin:
                        x=x_
                    ###################################
                    
                                        
                if torch.abs(Emin - E_old) < diff:
                    break
        return E_best.cpu().numpy()

In [28]:
def main():
    # settings
    parser = argparse.ArgumentParser('Gumbel-softmax optimizing SK model energy')
    parser.add_argument('--n', type=int, default=1024,
                        help='size (default: 1024)')
    parser.add_argument('--bs', type=int, default=128,
                        help='batch size (default: 128)')
    parser.add_argument('--max_iters', type=int, default=50000,
                        help='iterations (default: 50000)')
    parser.add_argument('--lr', type=float, default=1.,
                        help='learning rate (default: 1)')
    parser.add_argument('--eta', type=float, default=1e-3,
                        help='weight decay (default: 1e-3)')
    parser.add_argument('--init-tau', type=float, default=20.,
                        help='initial tau in Gumbel-softmax (default: 20)')
    parser.add_argument('--final-tau', type=float, default=1.,
                        help='final tau in Gumbel-softmax (default: 1)')
    parser.add_argument('--instances', type=int, default=100,
                        help='number of ensembles (default: 1024)')
    parser.add_argument('--device', type=str, default='cuda:0',
                        help='cuda device (default: cuda:0)')
    args = parser.parse_args(args=[])
    n = args.n  # size
    bs = args.bs # batch size
    max_iters = args.max_iters
    init_tau = args.init_tau
    final_tau = args.final_tau
    lr = args.lr
    eta = args.eta
    instances = args.instances
    device = args.device
    torch.manual_seed(2050)

    # training
    results_arr = []
    for i in range(instances):
        sk = SKModel(n, device=device)
        energy = sk.gumbel_optimization(bs, max_iters, lr, eta, init_tau, final_tau)
        print('# %i \t energy: %.5f' % (i, energy))
        results_arr.append(energy)

   # print mean energy and std
    data = np.array(results_arr)
    data_mean = data.mean()
    data_std = np.sqrt(np.var(data, ddof=1))
    print('Batch Gumbel-softmax N: %i, bs: %i, instances: %i, mean: %.5f, std: %.5f' %
          (n, bs, instances, data_mean, data_std))


if __name__ == '__main__':
    start = time.time()
    main()
    end = time.time()
    print('Running time: %.5f s \n' % (end - start))


0 Current best result: 1.00000000
Energy_sorted:
 [-0.05446712 -0.05437486 -0.04368582 -0.04135018 -0.03982198 -0.03951745
 -0.03733383 -0.03646356 -0.03508395 -0.03255935 -0.03253445 -0.03036683
 -0.02973241 -0.02964533 -0.02947187 -0.02903254]
label_sorted:
 [ 99  32  84  45 107 124  56  72  29  24  98  28 114  91 121  96]
99
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
32
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
84
tensor([-1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
45
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
107
tensor([-1.,  1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
124
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
56
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
72
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
29
tensor([ 1., -1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
24
tensor([-1.,  1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
98
tensor([ 1.,  1., 

600 Current best result: -0.09390767
Energy_sorted:
 [-0.05055113 -0.04664255 -0.04505819 -0.0416052  -0.03941452 -0.03926935
 -0.03660139 -0.03607442 -0.03585934 -0.03520074 -0.03120151 -0.02981333
 -0.02824805 -0.0270385  -0.026391   -0.02541035]
label_sorted:
 [  7   4   8  34  60  49  86 108 113 107 112  35  98  74  11  36]
7
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')
4
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
8
tensor([-1.,  1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
34
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
60
tensor([-1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
49
tensor([-1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
86
tensor([-1., -1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
108
tensor([-1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
113
tensor([-1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
107
tensor([-1.,  1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
112
tensor([-1.,  1., -1.,

1200 Current best result: -0.11196916
Energy_sorted:
 [-0.06089921 -0.05303711 -0.0482222  -0.0413551  -0.03756249 -0.03708905
 -0.03619216 -0.03465541 -0.03000462 -0.02964039 -0.02891332 -0.02803484
 -0.02762731 -0.02593729 -0.02517117 -0.02167479]
label_sorted:
 [ 38 122  52  73  71  43 120 118 108  68 121  24  33   0  81 125]
38
tensor([-1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
122
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')
52
tensor([ 1.,  1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
73
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
71
tensor([-1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
43
tensor([ 1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
120
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
118
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
108
tensor([ 1., -1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
68
tensor([-1.,  1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
121
tensor([ 1., -1.,

1800 Current best result: -0.11196916
Energy_sorted:
 [-0.07072246 -0.04942395 -0.04906658 -0.04904611 -0.04809102 -0.04585243
 -0.04463246 -0.04379202 -0.04084018 -0.04042334 -0.03864724 -0.03758626
 -0.03697743 -0.03451365 -0.03446042 -0.03292744]
label_sorted:
 [119  71  24   6  56 120  23  92  95 126  85  44  15 116  76  35]
119
tensor([-1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
71
tensor([ 1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
24
tensor([-1., -1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
6
tensor([-1.,  1., -1.,  ...,  1., -1., -1.], device='cuda:0')
56
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
120
tensor([-1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
23
tensor([-1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
92
tensor([-1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
95
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
126
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
85
tensor([ 1.,  

2400 Current best result: -0.11196916
Energy_sorted:
 [-0.04859304 -0.04592847 -0.04580831 -0.04086587 -0.04062319 -0.03834932
 -0.037163   -0.03527387 -0.03495    -0.03472264 -0.0320715  -0.03168369
 -0.03054423 -0.02827662 -0.02798428 -0.02798016]
label_sorted:
 [127  27 122  71  17  10 103  14 125  81  94  15   2  38  95  77]
127
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
27
tensor([ 1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
122
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
71
tensor([ 1.,  1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
17
tensor([-1., -1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
10
tensor([-1.,  1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
103
tensor([ 1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
14
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
125
tensor([ 1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
81
tensor([ 1., -1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
94
tensor([ 1.,

3000 Current best result: -0.11196916
Energy_sorted:
 [-0.05155199 -0.04270872 -0.04164426 -0.03700297 -0.0359668  -0.03345221
 -0.03301722 -0.03279451 -0.03123823 -0.03079081 -0.03075448 -0.0293879
 -0.02917985 -0.02866309 -0.02825739 -0.02633255]
label_sorted:
 [126   9 111  33  56  54 107  99  84  11  21  51 118  38 103  59]
126
tensor([ 1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
9
tensor([ 1.,  1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
111
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
33
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
56
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
54
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
107
tensor([-1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
99
tensor([-1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
84
tensor([-1., -1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
11
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
21
tensor([ 1., -1

3600 Current best result: -0.11196916
Energy_sorted:
 [-0.06608143 -0.05630213 -0.05168496 -0.0488774  -0.04804651 -0.04568136
 -0.04162718 -0.04005493 -0.03723054 -0.03438964 -0.03292172 -0.03184576
 -0.02872577 -0.0264206  -0.02608507 -0.02473917]
label_sorted:
 [ 81 102  28  75  79  53 124  13  95 110  31  43  80  72  83 114]
81
tensor([ 1., -1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
102
tensor([ 1.,  1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
28
tensor([ 1.,  1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
75
tensor([ 1.,  1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
79
tensor([ 1.,  1., -1.,  ...,  1., -1., -1.], device='cuda:0')
53
tensor([-1.,  1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
124
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
13
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
95
tensor([-1., -1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
110
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
31
tensor([ 1., 

4200 Current best result: -0.11196916
Energy_sorted:
 [-0.0593427  -0.05071406 -0.04271576 -0.04106079 -0.04050117 -0.03764367
 -0.03733912 -0.03614816 -0.03614175 -0.03567869 -0.03214014 -0.02863959
 -0.02807375 -0.0265955  -0.02612222 -0.0257064 ]
label_sorted:
 [ 85  37 102  47   6  17  62  58  65 121  52 100  75  36  41  21]
85
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
37
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
102
tensor([ 1.,  1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
47
tensor([-1., -1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
17
tensor([ 1.,  1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
62
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
58
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
65
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
121
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
52
tensor([-1.,  1

4800 Current best result: -0.11196916
Energy_sorted:
 [-0.05939604 -0.05854768 -0.05270819 -0.04375203 -0.04296815 -0.04252111
 -0.03908428 -0.03873596 -0.03779053 -0.03748404 -0.03722915 -0.03493254
 -0.03027612 -0.02931877 -0.02901771 -0.02849834]
label_sorted:
 [ 89  68  81  21  92  24  54  58  13  14 103  22 124  99 125 114]
89
tensor([-1.,  1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
68
tensor([-1.,  1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
81
tensor([-1.,  1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
21
tensor([ 1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
92
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
24
tensor([ 1.,  1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
54
tensor([ 1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
58
tensor([ 1.,  1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
13
tensor([-1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
14
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
103
tensor([ 1.,  1

5400 Current best result: -0.11196916
Energy_sorted:
 [-0.0652646  -0.05949545 -0.05806082 -0.05063811 -0.04755993 -0.04337667
 -0.04110029 -0.03984634 -0.03491242 -0.03437563 -0.03034428 -0.02809375
 -0.02799157 -0.02798878 -0.02675265 -0.02618787]
label_sorted:
 [127 117  33   1  98  69  56 119 100  13  52  83 108   2  32  35]
127
tensor([-1., -1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
117
tensor([ 1., -1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
33
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
1
tensor([ 1.,  1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
98
tensor([-1.,  1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
69
tensor([ 1., -1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
56
tensor([ 1., -1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
119
tensor([-1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
100
tensor([-1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
13
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
52
tensor([1., 1

6000 Current best result: -0.11196916
Energy_sorted:
 [-0.05812464 -0.05647683 -0.04619393 -0.04561211 -0.04175228 -0.04131029
 -0.03955541 -0.0384953  -0.03589658 -0.03184886 -0.03105329 -0.0296693
 -0.02904623 -0.02861769 -0.0268534  -0.0266206 ]
label_sorted:
 [ 23  24 104  87  74  51   7  61  75 112   2 110  72  86  33  57]
23
tensor([-1.,  1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
24
tensor([-1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
104
tensor([-1.,  1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
87
tensor([ 1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
74
tensor([ 1., -1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
51
tensor([-1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
7
tensor([-1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
61
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
75
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
112
tensor([-1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
2
tensor([-1., -1.,

6600 Current best result: -0.11196916
Energy_sorted:
 [-0.0562233  -0.04840374 -0.04217672 -0.03499839 -0.03434987 -0.02971997
 -0.02950749 -0.02899724 -0.0283431  -0.02675278 -0.02674528 -0.02615783
 -0.02346555 -0.023339   -0.02327071 -0.02268238]
label_sorted:
 [ 57  70  22  81  89   5  97 116  66 105  35  11  20  68 101   4]
57
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
70
tensor([ 1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
22
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
81
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
89
tensor([-1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
5
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
97
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
116
tensor([ 1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
66
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
105
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1

7200 Current best result: -0.11196916
Energy_sorted:
 [-0.06816803 -0.06344148 -0.06292661 -0.05861225 -0.04949769 -0.04881195
 -0.04290947 -0.04173568 -0.04168758 -0.03848814 -0.03739316 -0.03684609
 -0.03614214 -0.03527491 -0.03379675 -0.0333494 ]
label_sorted:
 [ 46  21  28 108  86 119  65  94 117  77  81 124  10  72  99   7]
46
tensor([ 1.,  1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
21
tensor([ 1., -1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
28
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
108
tensor([-1., -1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
86
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
119
tensor([-1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
65
tensor([-1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
94
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
117
tensor([ 1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
77
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
81
tensor([-1., 

7800 Current best result: -0.11196916
Energy_sorted:
 [-0.07688447 -0.067893   -0.05498609 -0.05316447 -0.05055405 -0.04480279
 -0.04340139 -0.04287834 -0.04205593 -0.04130996 -0.03863961 -0.0361924
 -0.03571751 -0.03255536 -0.03126831 -0.03108464]
label_sorted:
 [ 86   2 103  54  55  99  33 105  95  10  71 110 109 123  29 121]
86
tensor([-1., -1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
2
tensor([ 1., -1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
103
tensor([ 1.,  1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
54
tensor([ 1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
55
tensor([-1.,  1., -1.,  ...,  1., -1., -1.], device='cuda:0')
99
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
33
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
105
tensor([-1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
95
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
10
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
71
tensor([-1., -1.

8400 Current best result: -0.11196916
Energy_sorted:
 [-0.07289077 -0.04300556 -0.03981262 -0.03658653 -0.03611766 -0.03460643
 -0.03446735 -0.03244235 -0.03094437 -0.03080983 -0.02967084 -0.02927858
 -0.02880101 -0.02824141 -0.02732365 -0.02635459]
label_sorted:
 [ 59  20  67  60  95  55  46  87 102  52  80  50   7   2  47 106]
59
tensor([ 1.,  1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
20
tensor([-1., -1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
67
tensor([-1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
60
tensor([ 1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
95
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
55
tensor([-1., -1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
46
tensor([-1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
87
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
102
tensor([-1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
52
tensor([ 1.,  1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
80
tensor([-1., -1

9000 Current best result: -0.11196916
Energy_sorted:
 [-0.04679635 -0.04477838 -0.03857448 -0.03752384 -0.0372964  -0.03541199
 -0.03475476 -0.03459577 -0.0322437  -0.02981783 -0.02824511 -0.02624419
 -0.02603755 -0.02545214 -0.02542236 -0.02494548]
label_sorted:
 [ 12  15  11  70  20  10  89  82  88 111 122  24  48   9  56  68]
12
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
15
tensor([-1.,  1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
11
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
70
tensor([-1.,  1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
20
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
10
tensor([-1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
89
tensor([ 1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
82
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
88
tensor([ 1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
111
tensor([-1., -1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
122
tensor([-1.,  

9600 Current best result: -0.11196916
Energy_sorted:
 [-0.05764548 -0.05048271 -0.04716622 -0.04376694 -0.04249159 -0.04058612
 -0.03989197 -0.03818168 -0.03555311 -0.03512387 -0.03389547 -0.03357991
 -0.03317492 -0.03304139 -0.03303713 -0.03117777]
label_sorted:
 [ 81  82  17  64  15  34  32  46  41   2  98  44  11  10  70 111]
81
tensor([-1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
82
tensor([ 1.,  1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
17
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
64
tensor([ 1.,  1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
15
tensor([-1., -1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
34
tensor([ 1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
32
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
46
tensor([-1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
41
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
2
tensor([ 1.,  1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
98
tensor([ 1.,  1.,

10200 Current best result: -0.11196916
Energy_sorted:
 [-0.06901706 -0.06461541 -0.05429289 -0.05341457 -0.0506245  -0.04970593
 -0.04035585 -0.03734131 -0.03447036 -0.03418242 -0.03416587 -0.03403953
 -0.03398518 -0.03192029 -0.0313876  -0.03129271]
label_sorted:
 [  6 101  73   3  61 110  10  27  21  80  92  26  50  59  40  93]
6
tensor([-1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
101
tensor([ 1., -1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
73
tensor([-1.,  1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
3
tensor([ 1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
61
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
110
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
10
tensor([ 1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
27
tensor([-1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
21
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
80
tensor([ 1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
92
tensor([ 1., -1

10800 Current best result: -0.11196916
Energy_sorted:
 [-0.06688711 -0.05911852 -0.05615022 -0.05409671 -0.05384002 -0.05116113
 -0.04950108 -0.0462992  -0.04589488 -0.04588827 -0.0450198  -0.0449125
 -0.04448541 -0.04317479 -0.04137558 -0.03927523]
label_sorted:
 [ 15 117  49  67  83  99  66   4  22  96  41  82  91  64  14  52]
15
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
117
tensor([ 1.,  1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
49
tensor([-1.,  1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
67
tensor([ 1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
83
tensor([-1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
99
tensor([-1.,  1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
66
tensor([ 1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
4
tensor([-1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
22
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
96
tensor([ 1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
41
tensor([ 1., -1.

11400 Current best result: -0.11196916
Energy_sorted:
 [-0.06063534 -0.05765257 -0.05278751 -0.0510788  -0.04953181 -0.04807379
 -0.04795795 -0.04648444 -0.04152855 -0.04112142 -0.03885868 -0.03729553
 -0.03523201 -0.03343322 -0.03316781 -0.03282764]
label_sorted:
 [ 77  53  91  45  94 117  20  93  54 122  80 126 110  70  16  60]
77
tensor([-1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
53
tensor([-1.,  1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
91
tensor([-1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
45
tensor([-1., -1., -1.,  ..., -1., -1.,  1.], device='cuda:0')
94
tensor([-1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
117
tensor([ 1., -1.,  1.,  ..., -1., -1.,  1.], device='cuda:0')
20
tensor([-1., -1., -1.,  ..., -1.,  1.,  1.], device='cuda:0')
93
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')
54
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
122
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')
80
tensor([ 1.,  1., -1.,  .

12000 Current best result: -0.11396492
Energy_sorted:
 [-0.07198963 -0.06894522 -0.06325661 -0.06138909 -0.06039201 -0.05938726
 -0.05816676 -0.05720595 -0.05630747 -0.05446001 -0.05416276 -0.05068341
 -0.04912771 -0.04867862 -0.04826287 -0.04474693]
label_sorted:
 [ 82  97  59  94 111  73   3 107  50 108  98  69 126   8  78  86]
82
tensor([-1.,  1., -1.,  ...,  1., -1., -1.], device='cuda:0')
97
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
59
tensor([-1., -1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
94
tensor([-1., -1.,  1.,  ...,  1.,  1., -1.], device='cuda:0')
111
tensor([ 1.,  1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
73
tensor([-1.,  1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
3
tensor([-1.,  1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
107
tensor([-1.,  1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
50
tensor([-1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
108
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
98
tensor([-1., 

12600 Current best result: -0.23427320
Energy_sorted:
 [-0.21917641 -0.16194257 -0.15104319 -0.14373311 -0.14097376 -0.14072135
 -0.1400406  -0.13499415 -0.13374579 -0.13363984 -0.1322934  -0.13084465
 -0.12857357 -0.12782568 -0.12601928 -0.12548798]
label_sorted:
 [115  85  59 124  84   6  64 113  46  78  19  80 121  31   2 119]
115
tensor([-1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
85
tensor([ 1.,  1.,  1.,  ..., -1.,  1.,  1.], device='cuda:0')
59
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
124
tensor([ 1.,  1.,  1.,  ...,  1., -1., -1.], device='cuda:0')
84
tensor([-1., -1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
64
tensor([-1., -1., -1.,  ...,  1., -1., -1.], device='cuda:0')
113
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
46
tensor([ 1., -1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
78
tensor([ 1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
19
tensor([ 1., 

13200 Current best result: -0.57278347
Energy_sorted:
 [-0.54301846 -0.5395598  -0.52842355 -0.5234501  -0.51199895 -0.50910914
 -0.5066717  -0.50280833 -0.49568328 -0.49144945 -0.49067128 -0.48490572
 -0.48384833 -0.48126918 -0.48003215 -0.479989  ]
label_sorted:
 [ 32  80 115   2  71  30 113  85  84  45  46  54 124 119  91  60]
32
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
80
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
115
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
2
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
71
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
30
tensor([ 1., -1., -1.,  ..., -1., -1., -1.], device='cuda:0')
113
tensor([ 1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
85
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
84
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')
45
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
46
tensor([ 1., -1.,  1

13800 Current best result: -0.64970660
Energy_sorted:
 [-0.63401306 -0.630445   -0.62843955 -0.62268806 -0.6213991  -0.6198957
 -0.6191362  -0.6182809  -0.61623883 -0.61608934 -0.6157838  -0.6152735
 -0.6140291  -0.61335415 -0.61307436 -0.6127967 ]
label_sorted:
 [ 71  28   2  44  32 105  21 122  38  41 119 118  14  30  54  18]
71
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
28
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
2
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
44
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
32
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
105
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
21
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
122
tensor([ 1., -1., -1.,  ...,  1.,  1.,  1.], device='cuda:0')
38
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
41
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
119
tensor([ 1., -1

14400 Current best result: -0.66588175
Energy_sorted:
 [-0.6508293  -0.6498754  -0.64872086 -0.6486567  -0.648299   -0.6482608
 -0.64519095 -0.6435878  -0.6433671  -0.6432457  -0.64277303 -0.6423183
 -0.6417984  -0.64164984 -0.6416049  -0.6409005 ]
label_sorted:
 [ 52  23  96 101  29 107  71   1  18  68  87  64 108  44  94 127]
52
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
23
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
96
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
101
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
29
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
107
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
71
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
1
tensor([-1.,  1.,  1.,  ..., -1., -1., -1.], device='cuda:0')
18
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
68
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
87
tensor([ 1., -1.

15000 Current best result: -0.68240273
Energy_sorted:
 [-0.67798245 -0.6699802  -0.6663113  -0.66403866 -0.6636727  -0.6629716
 -0.662707   -0.6589008  -0.6586681  -0.6575588  -0.65748036 -0.65648764
 -0.6563094  -0.656096   -0.65543884 -0.6553211 ]
label_sorted:
 [ 94 127  18   7 107 104  52  75   1  62  39  87 116  10  71  35]
94
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
127
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
18
tensor([ 1., -1.,  1.,  ...,  1.,  1.,  1.], device='cuda:0')
7
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
107
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
104
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
52
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
75
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
1
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
62
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
39
tensor([-1.,  1

15600 Current best result: -0.69002736
Energy_sorted:
 [-0.67693484 -0.67453265 -0.6743606  -0.6728107  -0.67160714 -0.6715275
 -0.671048   -0.6707189  -0.6704809  -0.6689941  -0.6689706  -0.6688962
 -0.6681741  -0.6674732  -0.6669328  -0.666783  ]
label_sorted:
 [107  35 116  39 113   7  87  42  51  68  52 127   1  36  49  40]
107
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
116
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
113
tensor([ 1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
7
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
87
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
42
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
51
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
68
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
52
tensor([-1.,  1

16200 Current best result: -0.69745350
Energy_sorted:
 [-0.6904803  -0.68715054 -0.6823896  -0.682174   -0.67923665 -0.6785637
 -0.67806184 -0.6775402  -0.6767843  -0.67640173 -0.675177   -0.675133
 -0.67398834 -0.67372024 -0.67359483 -0.6734952 ]
label_sorted:
 [ 87  35  48  94 127  64 126  18 117  36  51  68  63  39  66  84]
87
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1., -1., -1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
94
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
127
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
64
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
126
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
18
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
117
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
36
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
51
tensor([-1.,  1

16800 Current best result: -0.70118427
Energy_sorted:
 [-0.6907176  -0.6902104  -0.69007695 -0.6888739  -0.6871612  -0.6866858
 -0.6848029  -0.6843917  -0.6831725  -0.6830685  -0.68271005 -0.682261
 -0.6821723  -0.6821281  -0.6820806  -0.6818583 ]
label_sorted:
 [ 69  94  39  87  64 127  43 107  53  48  35  36 113  91  58  73]
69
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
94
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
87
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
64
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
127
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
43
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
107
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
53
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1.

17400 Current best result: -0.70702851
Energy_sorted:
 [-0.7007476  -0.6972146  -0.69695616 -0.69420654 -0.69350016 -0.6929402
 -0.6926921  -0.69253385 -0.6922583  -0.69074404 -0.6902613  -0.68967414
 -0.6894096  -0.6888186  -0.6885865  -0.68807757]
label_sorted:
 [ 39 127  87  51  18 116  35  69  48  43  16 111  36  71 117  50]
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
127
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
87
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
51
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
18
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
116
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
69
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
43
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
16
tensor([ 1., -

18000 Current best result: -0.71281141
Energy_sorted:
 [-0.7051662  -0.7032222  -0.70027864 -0.7000324  -0.6997533  -0.69929767
 -0.6977647  -0.6967232  -0.6955053  -0.6949729  -0.694839   -0.69476783
 -0.69469786 -0.69459677 -0.69442195 -0.694348  ]
label_sorted:
 [ 39  53 127 116  36  78  79  43  51  17  48  87  94  35  40   1]
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
53
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
127
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
116
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
36
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
78
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
79
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
43
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
51
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
17
tensor([-1.,  1., -1.,  ...,  1.,  1., -1.], device='cuda:0')
48
tensor([-1., 

18600 Current best result: -0.71589023
Energy_sorted:
 [-0.70741636 -0.7049103  -0.70375264 -0.70304257 -0.7024954  -0.70210224
 -0.7017317  -0.701227   -0.70088094 -0.70023173 -0.6999671  -0.6998303
 -0.69878423 -0.69863576 -0.6981877  -0.69763327]
label_sorted:
 [ 36   7 116  43  16  51 107  69  87  39  79  53  49  94 127  75]
36
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
7
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
116
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
43
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
16
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
51
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
107
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
69
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
87
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
79
tensor([ 1., -1

19200 Current best result: -0.72245389
Energy_sorted:
 [-0.7153542  -0.7148743  -0.7125155  -0.71232456 -0.70983213 -0.7093645
 -0.7082492  -0.70809543 -0.7076974  -0.70751333 -0.7068511  -0.70649445
 -0.70618016 -0.706046   -0.7059155  -0.70574296]
label_sorted:
 [ 53  39  48  69  22  79  59 127  87  35  51  43  49  91  74   7]
53
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
69
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
22
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
79
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
59
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
127
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
87
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
51
tensor([-1.,  1

19800 Current best result: -0.72444570
Energy_sorted:
 [-0.718303   -0.71572846 -0.7156167  -0.71550333 -0.7153357  -0.7144711
 -0.7136357  -0.71341026 -0.71200377 -0.71164834 -0.7114482  -0.71142805
 -0.71124095 -0.7112166  -0.7104602  -0.7101508 ]
label_sorted:
 [116  48  36  43  39  81  51  69  16  49 107 100  59  34 114  87]
116
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
36
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
43
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
39
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
81
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
51
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
69
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
16
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
49
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
107
tensor([-1.,  

20400 Current best result: -0.72681892
Energy_sorted:
 [-0.7205279  -0.7192087  -0.71839917 -0.71789074 -0.7174391  -0.71740115
 -0.717355   -0.71708345 -0.7162794  -0.715906   -0.7155955  -0.71552503
 -0.71517307 -0.7151638  -0.71495074 -0.714786  ]
label_sorted:
 [  6 100  88 111  72  17  35  38   3  94  10  36  22  92 127  41]
6
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
100
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
88
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
111
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
72
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
17
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
38
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
3
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
94
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
10
tensor([ 1., -1

21000 Current best result: -0.72834969
Energy_sorted:
 [-0.7233511  -0.7215938  -0.72159255 -0.7198626  -0.7198408  -0.719553
 -0.71925855 -0.7186307  -0.7186202  -0.71857464 -0.7185731  -0.7184874
 -0.7182062  -0.71807456 -0.7178904  -0.717818  ]
label_sorted:
 [ 17 111  35   6  82  22  72  38 125 100  73  64  30   0  61  66]
17
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
111
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
82
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
22
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
72
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
38
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
100
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
73
tensor([ 1., -1.

21600 Current best result: -0.72965807
Energy_sorted:
 [-0.72828    -0.724808   -0.72450835 -0.7239979  -0.7235215  -0.72334325
 -0.72280455 -0.72258675 -0.72181535 -0.72142905 -0.7212081  -0.72065437
 -0.7205092  -0.72036994 -0.72024053 -0.7200134 ]
label_sorted:
 [100  97   6  73  30  53 125  35  31  12  47  15  82  92  99  17]
100
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
97
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
73
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
30
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
53
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
31
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
12
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
47
tensor([ 1., -

22200 Current best result: -0.73139447
Energy_sorted:
 [-0.73029554 -0.7267958  -0.7267202  -0.72661746 -0.7258207  -0.7247205
 -0.72330856 -0.72295785 -0.7224905  -0.7224052  -0.7222173  -0.7219511
 -0.72175103 -0.721661   -0.7216097  -0.7215829 ]
label_sorted:
 [106 125   6  82  97  74 111  35 109  14  73 100  93  15  83  17]
106
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
82
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
97
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
74
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
111
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
109
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
14
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
73
tensor([ 1., -

22800 Current best result: -0.73441207
Energy_sorted:
 [-0.730759   -0.7289861  -0.7286353  -0.72857773 -0.72826475 -0.7275964
 -0.7275895  -0.72752    -0.72739434 -0.7268245  -0.72631377 -0.7262311
 -0.72535837 -0.72528553 -0.725036   -0.7247163 ]
label_sorted:
 [ 95  82 121 124 111  92  48  35  21 125  97 100  29  17  73  53]
95
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
82
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
121
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
124
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
111
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
92
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
35
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
21
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
97
tensor([ 1., 

23400 Current best result: -0.73540926
Energy_sorted:
 [-0.7329881  -0.7325709  -0.730409   -0.7298135  -0.7293953  -0.72930247
 -0.7292799  -0.7289591  -0.72895575 -0.7280092  -0.7279005  -0.72759706
 -0.7273009  -0.7271998  -0.7271246  -0.7267824 ]
label_sorted:
 [125  73  29  21  95  30   6  92  53  48  17 121 100 124 111  97]
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
73
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
29
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
21
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
95
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
30
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
92
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
53
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
17
tensor([-1.,  1

24000 Current best result: -0.73702228
Energy_sorted:
 [-0.73408246 -0.73309064 -0.7325252  -0.73198634 -0.73194057 -0.73094034
 -0.73054636 -0.7300893  -0.72988987 -0.7294966  -0.7290735  -0.7286604
 -0.7283404  -0.7280887  -0.727984   -0.72768295]
label_sorted:
 [ 29 124  95 125  73 121   6  65  97  93 106  54 100  63  30  48]
29
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
124
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
95
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
73
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
121
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
6
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
65
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
97
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
93
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
106
tensor([ 1., 

24600 Current best result: -0.73762000
Energy_sorted:
 [-0.7362707  -0.73387134 -0.7326046  -0.7321676  -0.73193204 -0.7313939
 -0.73137337 -0.7311963  -0.7308854  -0.73080546 -0.7305394  -0.7303907
 -0.7301855  -0.7300195  -0.72998536 -0.7298237 ]
label_sorted:
 [ 95 121  29 110 125  82  48 124 100  61   1  12  73  35  31  21]
95
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
121
tensor([ 1., -1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
29
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
110
tensor([-1.,  1.,  1.,  ..., -1.,  1., -1.], device='cuda:0')
125
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
82
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
48
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
124
tensor([ 1., -1.,  1.,  ...,  1., -1.,  1.], device='cuda:0')
100
tensor([-1.,  1., -1.,  ..., -1.,  1., -1.], device='cuda:0')
61
tensor([ 1., -1., -1.,  ...,  1., -1.,  1.], device='cuda:0')
1
tensor([ 1., 

KeyboardInterrupt: 